name: Auto-merge dependabot PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    permissions:
      contents: write
      pull-requests: write
      checks: read
      statuses: read
      actions: read
    uses: jiikko/shared-workflows/.github/workflows/auto-merge-dependabot.yml@main
